# Development configuration
---
spring:
  profiles: development

datasource:
  url: jdbc:postgresql://localhost:5432/template
  username: postgres
  password: postgres
  driver-class-name: org.postgresql.Driver

jpa:
  default-schema: template
  ddl-auto: validate
  naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  dialect: org.hibernate.dialect.PostgreSQL9Dialect

# Production configuration
---
spring:
  profiles: production

datasource:
  url: jdbc:postgresql://localhost:5432/template
  username: postgres
  password: postgres
  driver-class-name: org.postgresql.Driver

jpa:
  default-schema: template
  ddl-auto: validate
  naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  dialect: org.hibernate.dialect.PostgreSQL9Dialect

